vpn_manager/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", index, name="index"),
    path("sites/", SitesListView.as_view(), name="sites-list"),
    path("sites/<int:pk>/", SitesDetailView.as_view(), name="sites-detail"),
    path("sites/create/", SitesCreateView.as_view(), name="sites-create"),
    path("sites/<int:pk>/update/", SitesUpdateView.as_view(), name="sites-update"),
    path("sites/<int:pk>/delete/", SitesDeleteView.as_view(), name="sites-delete"),
    path("<str:name>/<path:url>/", SitesConnectView.as_view(), name="sites-connect"),
]

app_name = "vpn-manager"

vpn_service/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("vpn_manager.urls", namespace="vpn_manager")),
    path("__debug__/", include("debug_toolbar.urls")),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vpn_manager/models.py
from django.db import models
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.models import AbstractUser


class Sites(models.Model):
    name = models.CharField(max_length=128)
    url = models.URLField(max_length=256)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

vpn_manager/views.py
import os
import requests
import shutil
import uuid
from bs4 import BeautifulSoup
from django.shortcuts import render
from .models import Sites
from django.views import generic, View
from django.urls import reverse_lazy
from .models import Sites
from urllib.parse import urljoin, urlparse, unquote
from django.utils.safestring import mark_safe


def create_unique_folder_name():
    return str(uuid.uuid4())


def create_directory(name):
    if not os.path.exists(name):
        os.makedirs(name)


def download_file(url, folder):
    if url.startswith("data:"):
        return None

    response = requests.get(url)
    if response.status_code == 200:
        filename = os.path.join(folder, os.path.basename(urlparse(url).path))
        with open(filename, "wb") as f:
            f.write(response.content)
        return filename
    return None


def download_page(url, site_name, folder="temp"):
    unique_folder = site_name
    folder_path = os.path.join(folder, unique_folder)
    create_directory(folder_path)

    images_folder = os.path.join(folder_path, 'images')
    includes_folder = os.path.join(folder_path, 'includes')
    video_folder = os.path.join(folder_path, 'video')

    create_directory(images_folder)
    create_directory(includes_folder)
    create_directory(video_folder)

    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    for link in soup.find_all("link", {"rel": "stylesheet"}):
        css_url = urljoin(url, link["href"])
        local_css_path = download_file(css_url, includes_folder)
        if local_css_path:
            link["href"] = f"/temp/{unique_folder}/includes/" + os.path.basename(local_css_path)

    for img in soup.find_all("img"):
        if img.has_attr("src"):
            img_url = urljoin(url, img["src"])
            local_img_path = download_file(img_url, images_folder)
            if local_img_path:
                img["src"] = f"/temp/{unique_folder}/images/" + os.path.basename(local_img_path)

    for script in soup.find_all("script", {"src": True}):
        js_url = urljoin(url, script["src"])
        local_js_path = download_file(js_url, includes_folder)
        if local_js_path:
            script["src"] = f"/temp/{unique_folder}/includes/" + os.path.basename(local_js_path)

    return str(soup)


def index(request):
    return render(
        request, "vpn_manager/index.html",
    )


class SitesListView(generic.ListView):
    model = Sites
    context_object_name = "sites_list"
    template_name = "vpn_manager/sites_list.html"

    def get_queryset(self):
        queryset = Sites.objects.order_by("name")
        name = self.request.GET.get("name", "")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class SitesDetailView(generic.DetailView):
    model = Sites
    template_name = "vpn_manager/sites_detail.html"


class SitesCreateView(generic.CreateView):
    model = Sites
    fields = ["name", "url", "description"]
    template_name = "vpn_manager/sites_form.html"
    success_url = reverse_lazy("vpn_manager:sites-list")


class SitesUpdateView(generic.UpdateView):
    model = Sites
    fields = ["name", "url", "description"]
    template_name = "vpn_manager/sites_form.html"
    success_url = reverse_lazy("vpn_manager:sites-list")


class SitesDeleteView(generic.DeleteView):
    model = Sites
    template_name = "vpn_manager/sites_confirm_delete.html"
    success_url = reverse_lazy("vpn_manager:sites-list")


class SitesConnectView(View):
    model = Sites
    template_name = "vpn_manager/sites_connect.html"
    def get(self, request, url, name, *args, **kwargs):
        decoded_url = unquote(url)
        site_name = f"{name}"
        site_html = download_page(decoded_url, site_name)
        context = {
            'site_html': site_html
        }
        return render(request, self.template_name, context)

templates/base.html
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>VPN Manager</title>
        
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            {% block header %}
            {% endblock header %}

            {% block content %}
            {% endblock content %}
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

templates/vpn_manager/index.html
{% extends "base.html" %}

{% block content %}

    <h1>Test</h1>

{% endblock %}

templates/vpn_manager/sites_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="section section-md">
    <div class="container">
      <div class="row mb-5 mb-lg-5">
        <div class="col-lg-4 col-sm-6">
          <h1>Delete ?</h1>
          <a class="btn btn-outline-success">
            Cancel
          </a>
          <form action="" method="post">
            {% csrf_token %}

            <input type="submit" value="Yes, delete" class="btn btn-outline-danger">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/vpn_manager/sites_connect.html
{% autoescape off %}
    {{ site_html|safe }}
{% endautoescape %}

templates/vpn_manager/sites_detail.html
{% extends "base.html" %}
{% block content %}
    <h1>Test</h1>
{% endblock %}

templates/vpn_manager/sites_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="section section-md">
    <div class="container">
      <div class="row mb-4 mb-lg-5">
        <div class="col-lg-4 col-sm-6">
          <span class="h1">{{ object|yesno:"Update,Create" }} sites</span>
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit" class="btn btn-primary">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/vpn_manager/sites_list.html
{% extends "base.html" %}

{% block content %}
<div class="section section-md">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="mb-4">
          <span class="h5">Sites connection table<a href="{% url 'vpn-manager:sites-create' %}" class="btn btn btn-outline-success link-to-page">
           Create
    </a></span>
        </div>
        <div class="mb-5">
          {% if sites_list %}
          <table class="table">
            <tr>
              <th scope="col">Sites</th>
            </tr>
            {% for site in sites_list %}
              <tr>
                <td>
                <a href="{% url 'vpn-manager:sites-connect' name=site.name url=site.url %}">
                    {{ site.name }}
                </a>
              <a href="{% url 'vpn-manager:sites-update' pk=site.id %}" class="badge bg-tertiary">
                update
              </a>
              <a href="{% url 'vpn-manager:sites-delete' pk=site.id %}" class="badge bg-danger">
                delete
              </a>
              <a href="{% url 'vpn-manager:sites-detail' pk=site.id %}" class="badge bg-tertiary">
                detail
            </a>
                </td>
              </tr>
            <!-- <tr>
                <td>
                  <a href="{% url 'vpn-manager:sites-detail' pk=site.id %}">
              {{ site.name }}</a>
              <a href="{% url 'vpn-manager:sites-update' pk=site.id %}" class="badge bg-tertiary">
                update
              </a>
              <a href="{% url 'vpn-manager:sites-delete' pk=site.id %}" class="badge bg-danger">
                delete
              </a>
                </td>
              </tr> -->
            {% endfor %}
          </table>
          {% else %}
          No Sites provided
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}